### ISSUE TITLE
differentiate with radar api

### ISSUE THREAD

**Issue by jlc467** [IBM-Bluemix/insights-weather#12]
Any plans for a radar api e.g. http://www.wunderground.com/weather/api/d/docs?d=layers/radar&MR=1 ?

**Comment by l2fprod** [comment]
Hi John, this project demoes the current capabilities of the Insights for Weather service in Bluemix. I would suggest you post your questions to https://developer.ibm.com/answers/topics/insights-weather/?smartspace=bluemix this is monitored by the product management and development teams of the Insights for Weather service.
thank you.
